In [25]:
from LinearAlgebra import *
import timeit

In [26]:
s = 10
A = np.random.randint(-4,4,size=(s,s))
print("size :",A.shape)
print(A)
S = np.dot(A.T,A)

size : (10, 10)
[[-1  2  2 -1 -2 -1  3  0  2 -1]
 [-1 -3  2  1 -2  3 -3  2  0  2]
 [-2  2 -1  1 -2 -2  0 -1  2 -3]
 [-1  2  1  3 -2  2  0 -1  0  0]
 [ 2  1  0 -4  2 -2  0 -3  3  2]
 [-4  2  2 -3  1 -4 -2 -2  3  2]
 [-1 -1  0 -4 -2 -1  1 -1 -1 -3]
 [-1 -3 -2 -4 -1 -3 -2  0  1 -2]
 [ 0 -4 -3  0  2  3  2 -4 -2 -3]
 [ 2  1  1  0 -4 -3  0 -3 -1 -3]]


In [27]:
print("Test if A*A.T is symetric :")
print(is_sym(S))

Test if A*A.T is symetric :
True


In [28]:
print("For matrix",A.shape)
start = timeit.default_timer()
detA = determinant_naive(A)
stop = timeit.default_timer()
print("determinant of A (naive method):",detA)
print("time :",stop-start,"secs")
start = timeit.default_timer()
detA = determinant_gauss(A)
stop = timeit.default_timer()
print("determinant of A (gaussian method):",detA)
print("time :",stop-start,"secs")
start = timeit.default_timer()
detA = np.linalg.det(A)
stop = timeit.default_timer()
print("determinant of A (numpy linalg mehtod):",detA)
print("time :",stop-start,"secs")

For matrix (10, 10)
determinant of A (naive method): 1357768
time : 4.18889711700001 secs
determinant of A (gaussian method): 1357767.9999999998
time : 0.0002809190000050421 secs
determinant of A (numpy linalg mehtod): 1357768.0000000016
time : 9.083499999462674e-05 secs


In [29]:
s2 = 1000
A2 = np.random.rand(s2,s2)/10
print("size :",A2.shape)
print(A2)

size : (1000, 1000)
[[0.04375748 0.02911174 0.00430859 ... 0.0950356  0.07107326 0.06544776]
 [0.02029941 0.00455144 0.02319366 ... 0.03298801 0.08989185 0.02952146]
 [0.04992465 0.05319509 0.01509    ... 0.0711531  0.07553662 0.03136901]
 ...
 [0.00738113 0.05724674 0.0230351  ... 0.04892961 0.0879484  0.01385821]
 [0.03417962 0.0592801  0.03212101 ... 0.0589668  0.08380029 0.06648904]
 [0.06224428 0.00227853 0.02625622 ... 0.08413695 0.07373186 0.06192358]]


In [30]:
print("For matrix",A2.shape)
start = timeit.default_timer()
detA2 = determinant_gauss(A2)
stop = timeit.default_timer()
print("determinant of A (gaussian method):",detA2)
print("time :",stop-start,"secs")
start = timeit.default_timer()
detA2 = np.linalg.det(A2)
stop = timeit.default_timer()
print("determinant of A (numpy linalg mehtod):",detA2)
print("time :",stop-start,"secs")

For matrix (1000, 1000)
determinant of A (gaussian method): 4.6682354237026185e-256
time : 2.088267174000009 secs
determinant of A (numpy linalg mehtod): 4.668235423782369e-256
time : 0.016725781000005213 secs


In [31]:
print("Test if A*A.T is positive definite")
print(is_def_pos_sylvester(S))

Test if A*A.T is positive definite
True


In [32]:
print("Test the inverse of A with gaussian with A*inv(A) == Id")
invA = inverse_gauss(A)
print(np.round(np.dot(invA,A)+0.0001,3))

Test the inverse of A with gaussian with A*inv(A) == Id
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [33]:
print("Test Cholesky algorithme on S=A*A.T")
L = cholesky(S)
if (np.linalg.norm(np.dot(L,L.T)-S)<0.001):
    print(True)
else :
    print(False)

Test Cholesky algorithme on S=A*A.T
True


In [34]:
s=4
A = np.random.randint(-4,4,size=(s,s))
print("size :",A.shape)
print(A)

size : (4, 4)
[[-1  0 -1 -4]
 [ 0 -2  2 -4]
 [ 0  2  2 -3]
 [-4 -1 -4  1]]


In [35]:
print("Test the diagonalizable algorithm with power iteration method")
print("For matrix",A.shape)
A_eigvals,A_eigvect = eigen(A)
while(len(A_eigvals) != s):
    A = np.random.randint(-4,4,size=(s,s))
    A_eigvals,A_eigvect = eigen(A)
print("Eigen value :",A_eigvals)

Test the diagonalizable algorithm with power iteration method
For matrix (4, 4)
Eigen value : [6.82179, -4.77507, -3.32199, 1.27527]


In [36]:
print("Test the transition Matrix P")
P = eigen_matrix(A)
print("D = inv(P)*A*P")
print(np.round(np.dot(np.dot(inverse_gauss(P),A),P)+0.000000001,5))

Test the transition Matrix P
D = inv(P)*A*P
[[ 6.82179  0.       0.       0.     ]
 [ 0.      -4.77507  0.       0.     ]
 [ 0.       0.      -3.32199  0.     ]
 [ 0.       0.       0.       1.27527]]


In [49]:
s = 500
A = np.random.rand(s,s)/10
S = np.dot(A.T,A)
print("size :",S.shape)
print("Test the diagonalizable algorithm with power iteration method")
print("For matrix",S.shape)
start = timeit.default_timer()
S_eigvals,S_eigvect = eigen(S)
stop = timeit.default_timer()
print("time :",stop-start,"secs")

size : (500, 500)
Test the diagonalizable algorithm with power iteration method
For matrix (500, 500)
time : 9.664903896999931 secs


In [60]:
print("eigen values :\n",S_eigvals)
S_eigvals2 = np.linalg.eigvals(S)
print("eigen values with numpy linalg :\n",S_eigvals2)
if (sum(S_eigvals)-S_eigvals2.sum() < 1) :
    print("True")
else:
    print("False")

eigen values :
 [626.16408, 1.66215, 1.61296, 1.5956, 1.55764, 1.54308, 1.52655, 1.51806, 1.50574, 1.47766, 1.44208, 1.42879, 1.42474, 1.40829, 1.39762, 1.36921, 1.37265, 1.36718, 1.3535, 1.33739, 1.333, 1.32483, 1.31724, 1.30641, 1.29291, 1.28215, 1.28555, 1.2754, 1.26215, 1.24864, 1.24022, 1.23464, 1.22774, 1.22047, 1.2139, 1.20512, 1.1894, 1.18131, 1.1738, 1.16484, 1.15458, 1.14172, 1.13741, 1.1323, 1.12735, 1.12337, 1.11767, 1.10499, 1.0992, 1.08602, 1.07839, 1.07412, 1.06973, 1.06327, 1.05495, 1.04578, 1.03852, 1.02779, 1.0259, 1.01728, 1.01283, 1.00281, 1.0009, 0.98787, 0.98434, 0.98102, 0.97663, 0.97148, 0.9697, 0.96038, 0.94816, 0.94689, 0.93957, 0.93411, 0.93044, 0.91504, 0.91026, 0.90349, 0.89877, 0.89549, 0.89517, 0.88446, 0.88002, 0.87175, 0.86534, 0.85753, 0.84885, 0.84132, 0.83417, 0.8274, 0.82319, 0.82044, 0.81446, 0.81262, 0.81249, 0.80947, 0.80571, 0.79975, 0.79421, 0.78837, 0.78441, 0.77996, 0.77465, 0.76687, 0.7658, 0.75609, 0.75358, 0.7501, 0.74099, 0.74042, 0.73659